//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemanticLinkHelper.WordFormsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="gldesc.dic", Namespace="http://schemas.datacontract.org/2004/07/gldescript")]
    internal enum gldescdic : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INFL_DIC = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TRANSCR_DIC = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PHRAS_DIC = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SYN_DIC = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ANT_DIC = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListElement", Namespace="http://ulif.org.ua/lib5/")]
    [System.SerializableAttribute()]
    internal partial struct ListElement : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool aField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool fField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool sField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int uidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string wField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool a {
            get {
                return this.aField;
            }
            set {
                if ((this.aField.Equals(value) != true)) {
                    this.aField = value;
                    this.RaisePropertyChanged("a");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool f {
            get {
                return this.fField;
            }
            set {
                if ((this.fField.Equals(value) != true)) {
                    this.fField = value;
                    this.RaisePropertyChanged("f");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool s {
            get {
                return this.sField;
            }
            set {
                if ((this.sField.Equals(value) != true)) {
                    this.sField = value;
                    this.RaisePropertyChanged("s");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int uid {
            get {
                return this.uidField;
            }
            set {
                if ((this.uidField.Equals(value) != true)) {
                    this.uidField = value;
                    this.RaisePropertyChanged("uid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string w {
            get {
                return this.wField;
            }
            set {
                if ((object.ReferenceEquals(this.wField, value) != true)) {
                    this.wField = value;
                    this.RaisePropertyChanged("w");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="phrasdict.phraseology", Namespace="http://schemas.datacontract.org/2004/07/fdict")]
    [System.SerializableAttribute()]
    internal partial struct phrasdictphraseology : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int aidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private sbyte lField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phrasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sortField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int aid {
            get {
                return this.aidField;
            }
            set {
                if ((this.aidField.Equals(value) != true)) {
                    this.aidField = value;
                    this.RaisePropertyChanged("aid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal sbyte l {
            get {
                return this.lField;
            }
            set {
                if ((this.lField.Equals(value) != true)) {
                    this.lField = value;
                    this.RaisePropertyChanged("l");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string phras {
            get {
                return this.phrasField;
            }
            set {
                if ((object.ReferenceEquals(this.phrasField, value) != true)) {
                    this.phrasField = value;
                    this.RaisePropertyChanged("phras");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int sort {
            get {
                return this.sortField;
            }
            set {
                if ((this.sortField.Equals(value) != true)) {
                    this.sortField = value;
                    this.RaisePropertyChanged("sort");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="morphstr", Namespace="http://ulif.org.ua/lib5/")]
    [System.SerializableAttribute()]
    internal partial struct morphstr : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string scodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string wordField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string scode {
            get {
                return this.scodeField;
            }
            set {
                if ((object.ReferenceEquals(this.scodeField, value) != true)) {
                    this.scodeField = value;
                    this.RaisePropertyChanged("scode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string word {
            get {
                return this.wordField;
            }
            set {
                if ((object.ReferenceEquals(this.wordField, value) != true)) {
                    this.wordField = value;
                    this.RaisePropertyChanged("word");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WordUniAndPartAndOmon", Namespace="http://ulif.org.ua/lib5/")]
    [System.SerializableAttribute()]
    internal partial struct WordUniAndPartAndOmon : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string f6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string f7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string formaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort[] gramField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte omonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string partField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte part_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string scommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int uniField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string f6 {
            get {
                return this.f6Field;
            }
            set {
                if ((object.ReferenceEquals(this.f6Field, value) != true)) {
                    this.f6Field = value;
                    this.RaisePropertyChanged("f6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string f7 {
            get {
                return this.f7Field;
            }
            set {
                if ((object.ReferenceEquals(this.f7Field, value) != true)) {
                    this.f7Field = value;
                    this.RaisePropertyChanged("f7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string forma {
            get {
                return this.formaField;
            }
            set {
                if ((object.ReferenceEquals(this.formaField, value) != true)) {
                    this.formaField = value;
                    this.RaisePropertyChanged("forma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal ushort[] gram {
            get {
                return this.gramField;
            }
            set {
                if ((object.ReferenceEquals(this.gramField, value) != true)) {
                    this.gramField = value;
                    this.RaisePropertyChanged("gram");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal byte omon {
            get {
                return this.omonField;
            }
            set {
                if ((this.omonField.Equals(value) != true)) {
                    this.omonField = value;
                    this.RaisePropertyChanged("omon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string part {
            get {
                return this.partField;
            }
            set {
                if ((object.ReferenceEquals(this.partField, value) != true)) {
                    this.partField = value;
                    this.RaisePropertyChanged("part");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal byte part_id {
            get {
                return this.part_idField;
            }
            set {
                if ((this.part_idField.Equals(value) != true)) {
                    this.part_idField = value;
                    this.RaisePropertyChanged("part_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string scomment {
            get {
                return this.scommentField;
            }
            set {
                if ((object.ReferenceEquals(this.scommentField, value) != true)) {
                    this.scommentField = value;
                    this.RaisePropertyChanged("scomment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int uni {
            get {
                return this.uniField;
            }
            set {
                if ((this.uniField.Equals(value) != true)) {
                    this.uniField = value;
                    this.RaisePropertyChanged("uni");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="typeWord", Namespace="http://ulif.org.ua/lib5/")]
    internal enum typeWord : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Lemmat = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Omon = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nelamat = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="partgramInfo", Namespace="http://ulif.org.ua/lib5/")]
    [System.SerializableAttribute()]
    internal partial class partgramInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int commonidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte id_partsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string namepartField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int commonid {
            get {
                return this.commonidField;
            }
            set {
                if ((this.commonidField.Equals(value) != true)) {
                    this.commonidField = value;
                    this.RaisePropertyChanged("commonid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal byte id_parts {
            get {
                return this.id_partsField;
            }
            set {
                if ((this.id_partsField.Equals(value) != true)) {
                    this.id_partsField = value;
                    this.RaisePropertyChanged("id_parts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string namepart {
            get {
                return this.namepartField;
            }
            set {
                if ((object.ReferenceEquals(this.namepartField, value) != true)) {
                    this.namepartField = value;
                    this.RaisePropertyChanged("namepart");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommonPartsInfo", Namespace="http://ulif.org.ua/lib5/")]
    [System.SerializableAttribute()]
    internal partial class CommonPartsInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int commonIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string commonPartNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] grsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int commonId {
            get {
                return this.commonIdField;
            }
            set {
                if ((this.commonIdField.Equals(value) != true)) {
                    this.commonIdField = value;
                    this.RaisePropertyChanged("commonId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string commonPartName {
            get {
                return this.commonPartNameField;
            }
            set {
                if ((object.ReferenceEquals(this.commonPartNameField, value) != true)) {
                    this.commonPartNameField = value;
                    this.RaisePropertyChanged("commonPartName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string[] grs {
            get {
                return this.grsField;
            }
            set {
                if ((object.ReferenceEquals(this.grsField, value) != true)) {
                    this.grsField = value;
                    this.RaisePropertyChanged("grs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ulif.org.ua/services/lib5", ConfigurationName="WordFormsService.Ilib5")]
    internal interface Ilib5 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ulif.org.ua/services/lib5/IDataPageRetriever/SupplyPageOfData", ReplyAction="http://ulif.org.ua/services/lib5/IDataPageRetriever/SupplyPageOfDataResponse")]
        SemanticLinkHelper.WordFormsService.ListElement[] SupplyPageOfData(int lowerPageBoundary, int rowsPerPage, SemanticLinkHelper.WordFormsService.gldescdic dicFlag, bool singledict);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ulif.org.ua/services/lib5/Ilib5/ReestrGetID", ReplyAction="http://ulif.org.ua/services/lib5/Ilib5/ReestrGetIDResponse")]
        int ReestrGetID(int i, SemanticLinkHelper.WordFormsService.gldescdic dict, bool singledict);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ulif.org.ua/services/lib5/Ilib5/ReestrGetLen", ReplyAction="http://ulif.org.ua/services/lib5/Ilib5/ReestrGetLenResponse")]
        int ReestrGetLen(SemanticLinkHelper.WordFormsService.gldescdic dict);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ulif.org.ua/services/lib5/Ilib5/ReestrGetWord", ReplyAction="http://ulif.org.ua/services/lib5/Ilib5/ReestrGetWordResponse")]
        string ReestrGetWord(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ulif.org.ua/services/lib5/Ilib5/GenerateWPar", ReplyAction="http://ulif.org.ua/services/lib5/Ilib5/GenerateWParResponse")]
        byte[] GenerateWPar(string word, int id, string fstyle, SemanticLinkHelper.WordFormsService.gldescdic dtype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ulif.org.ua/services/lib5/Ilib5/GenerateWPar2", ReplyAction="http://ulif.org.ua/services/lib5/Ilib5/GenerateWPar2Response")]
        string GenerateWPar2(string word, int id, string fstyle, SemanticLinkHelper.WordFormsService.gldescdic dtype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ulif.org.ua/services/lib5/Ilib5/GenerateWPar3", ReplyAction="http://ulif.org.ua/services/lib5/Ilib5/GenerateWPar3Response")]
        string GenerateWPar3(string word, int id, string fstyle, SemanticLinkHelper.WordFormsService.gldescdic dtype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ulif.org.ua/services/lib5/Ilib5/SearchWord", ReplyAction="http://ulif.org.ua/services/lib5/Ilib5/SearchWordResponse")]
        int SearchWord(out bool r, string w, SemanticLinkHelper.WordFormsService.gldescdic dict, bool singledict);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ulif.org.ua/services/lib5/Ilib5/SearchDicWord", ReplyAction="http://ulif.org.ua/services/lib5/Ilib5/SearchDicWordResponse")]
        int SearchDicWord(out bool r, string w, SemanticLinkHelper.WordFormsService.gldescdic d, bool singledict);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ulif.org.ua/services/lib5/Ilib5/SearchOrderNum", ReplyAction="http://ulif.org.ua/services/lib5/Ilib5/SearchOrderNumResponse")]
        int SearchOrderNum(out bool res, int id, SemanticLinkHelper.WordFormsService.gldescdic dict, bool singledict);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ulif.org.ua/services/lib5/Ilib5/existdict", ReplyAction="http://ulif.org.ua/services/lib5/Ilib5/existdictResponse")]
        bool existdict(int uid, SemanticLinkHelper.WordFormsService.gldescdic d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ulif.org.ua/services/lib5/Ilib5/existdicts", ReplyAction="http://ulif.org.ua/services/lib5/Ilib5/existdictsResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="s")]
        bool existdicts(out bool f, out bool a, int uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ulif.org.ua/services/lib5/Ilib5/DictPrepare", ReplyAction="http://ulif.org.ua/services/lib5/Ilib5/DictPrepareResponse")]
        byte[] DictPrepare(int uid, string art, string fstyle, SemanticLinkHelper.WordFormsService.gldescdic d, bool singledict);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ulif.org.ua/services/lib5/Ilib5/DictPrepare2", ReplyAction="http://ulif.org.ua/services/lib5/Ilib5/DictPrepare2Response")]
        string DictPrepare2(int uid, string art, string fstyle, SemanticLinkHelper.WordFormsService.gldescdic d, bool singledict);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ulif.org.ua/services/lib5/Ilib5/phrasPrepare", ReplyAction="http://ulif.org.ua/services/lib5/Ilib5/phrasPrepareResponse")]
        byte[] phrasPrepare(out SemanticLinkHelper.WordFormsService.phrasdictphraseology[] phras, int uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ulif.org.ua/services/lib5/Ilib5/getpharticle", ReplyAction="http://ulif.org.ua/services/lib5/Ilib5/getpharticleResponse")]
        string getpharticle(int aid, sbyte l, string fstyle, bool singledict);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ulif.org.ua/services/lib5/Ilib5/getpharticle2", ReplyAction="http://ulif.org.ua/services/lib5/Ilib5/getpharticle2Response")]
        string getpharticle2(int aid, sbyte l, string fstyle, bool singledict);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ulif.org.ua/services/lib5/Ilib5/phcmp", ReplyAction="http://ulif.org.ua/services/lib5/Ilib5/phcmpResponse")]
        int phcmp(string word1, string word2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ulif.org.ua/services/lib5/Ilib5/GetAppName", ReplyAction="http://ulif.org.ua/services/lib5/Ilib5/GetAppNameResponse")]
        string GetAppName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ulif.org.ua/services/lib5/Ilib5/checkver", ReplyAction="http://ulif.org.ua/services/lib5/Ilib5/checkverResponse")]
        bool checkver(out string[] a, string sver);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ulif.org.ua/services/lib5/Ilib5/processmorph", ReplyAction="http://ulif.org.ua/services/lib5/Ilib5/processmorphResponse")]
        SemanticLinkHelper.WordFormsService.morphstr[] processmorph(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ulif.org.ua/services/lib5/Ilib5/getcwf", ReplyAction="http://ulif.org.ua/services/lib5/Ilib5/getcwfResponse")]
        string getcwf(string w);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ulif.org.ua/services/lib5/Ilib5/processaccent", ReplyAction="http://ulif.org.ua/services/lib5/Ilib5/processaccentResponse")]
        string processaccent(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ulif.org.ua/services/lib5/Ilib5/processtranscr", ReplyAction="http://ulif.org.ua/services/lib5/Ilib5/processtranscrResponse")]
        string processtranscr(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ulif.org.ua/services/lib5/Ilib5/getAllPart", ReplyAction="http://ulif.org.ua/services/lib5/Ilib5/getAllPartResponse")]
        bool getAllPart(out byte[] res, string inputWord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ulif.org.ua/services/lib5/Ilib5/getAllFirstWFormsWithParts", ReplyAction="http://ulif.org.ua/services/lib5/Ilib5/getAllFirstWFormsWithPartsResponse")]
        SemanticLinkHelper.WordFormsService.WordUniAndPartAndOmon[] getAllFirstWFormsWithParts(string inputWord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ulif.org.ua/services/lib5/Ilib5/getsemcomm", ReplyAction="http://ulif.org.ua/services/lib5/Ilib5/getsemcommResponse")]
        string getsemcomm(out string f6, out string f7, int uni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ulif.org.ua/services/lib5/Ilib5/getTypeWords", ReplyAction="http://ulif.org.ua/services/lib5/Ilib5/getTypeWordsResponse")]
        SemanticLinkHelper.WordFormsService.typeWord[] getTypeWords(string[] inputWords);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ulif.org.ua/services/lib5/Ilib5/getGramParams", ReplyAction="http://ulif.org.ua/services/lib5/Ilib5/getGramParamsResponse")]
        string[] getGramParams(out string partName, int idpart, ushort[] grs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ulif.org.ua/services/lib5/Ilib5/getPartIdAssotiations", ReplyAction="http://ulif.org.ua/services/lib5/Ilib5/getPartIdAssotiationsResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="partids")]
        int[] getPartIdAssotiations(out int[] commPartIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ulif.org.ua/services/lib5/Ilib5/getAllPartGramInfo", ReplyAction="http://ulif.org.ua/services/lib5/Ilib5/getAllPartGramInfoResponse")]
        SemanticLinkHelper.WordFormsService.partgramInfo[] getAllPartGramInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ulif.org.ua/services/lib5/Ilib5/getCommonPartsInfo", ReplyAction="http://ulif.org.ua/services/lib5/Ilib5/getCommonPartsInfoResponse")]
        SemanticLinkHelper.WordFormsService.CommonPartsInfo[] getCommonPartsInfo();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface Ilib5Channel : SemanticLinkHelper.WordFormsService.Ilib5, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class Ilib5Client : System.ServiceModel.ClientBase<SemanticLinkHelper.WordFormsService.Ilib5>, SemanticLinkHelper.WordFormsService.Ilib5 {
        
        public Ilib5Client() {
        }
        
        public Ilib5Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Ilib5Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Ilib5Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Ilib5Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SemanticLinkHelper.WordFormsService.ListElement[] SupplyPageOfData(int lowerPageBoundary, int rowsPerPage, SemanticLinkHelper.WordFormsService.gldescdic dicFlag, bool singledict) {
            return base.Channel.SupplyPageOfData(lowerPageBoundary, rowsPerPage, dicFlag, singledict);
        }
        
        public int ReestrGetID(int i, SemanticLinkHelper.WordFormsService.gldescdic dict, bool singledict) {
            return base.Channel.ReestrGetID(i, dict, singledict);
        }
        
        public int ReestrGetLen(SemanticLinkHelper.WordFormsService.gldescdic dict) {
            return base.Channel.ReestrGetLen(dict);
        }
        
        public string ReestrGetWord(int id) {
            return base.Channel.ReestrGetWord(id);
        }
        
        public byte[] GenerateWPar(string word, int id, string fstyle, SemanticLinkHelper.WordFormsService.gldescdic dtype) {
            return base.Channel.GenerateWPar(word, id, fstyle, dtype);
        }
        
        public string GenerateWPar2(string word, int id, string fstyle, SemanticLinkHelper.WordFormsService.gldescdic dtype) {
            return base.Channel.GenerateWPar2(word, id, fstyle, dtype);
        }
        
        public string GenerateWPar3(string word, int id, string fstyle, SemanticLinkHelper.WordFormsService.gldescdic dtype) {
            return base.Channel.GenerateWPar3(word, id, fstyle, dtype);
        }
        
        public int SearchWord(out bool r, string w, SemanticLinkHelper.WordFormsService.gldescdic dict, bool singledict) {
            return base.Channel.SearchWord(out r, w, dict, singledict);
        }
        
        public int SearchDicWord(out bool r, string w, SemanticLinkHelper.WordFormsService.gldescdic d, bool singledict) {
            return base.Channel.SearchDicWord(out r, w, d, singledict);
        }
        
        public int SearchOrderNum(out bool res, int id, SemanticLinkHelper.WordFormsService.gldescdic dict, bool singledict) {
            return base.Channel.SearchOrderNum(out res, id, dict, singledict);
        }
        
        public bool existdict(int uid, SemanticLinkHelper.WordFormsService.gldescdic d) {
            return base.Channel.existdict(uid, d);
        }
        
        public bool existdicts(out bool f, out bool a, int uid) {
            return base.Channel.existdicts(out f, out a, uid);
        }
        
        public byte[] DictPrepare(int uid, string art, string fstyle, SemanticLinkHelper.WordFormsService.gldescdic d, bool singledict) {
            return base.Channel.DictPrepare(uid, art, fstyle, d, singledict);
        }
        
        public string DictPrepare2(int uid, string art, string fstyle, SemanticLinkHelper.WordFormsService.gldescdic d, bool singledict) {
            return base.Channel.DictPrepare2(uid, art, fstyle, d, singledict);
        }
        
        public byte[] phrasPrepare(out SemanticLinkHelper.WordFormsService.phrasdictphraseology[] phras, int uid) {
            return base.Channel.phrasPrepare(out phras, uid);
        }
        
        public string getpharticle(int aid, sbyte l, string fstyle, bool singledict) {
            return base.Channel.getpharticle(aid, l, fstyle, singledict);
        }
        
        public string getpharticle2(int aid, sbyte l, string fstyle, bool singledict) {
            return base.Channel.getpharticle2(aid, l, fstyle, singledict);
        }
        
        public int phcmp(string word1, string word2) {
            return base.Channel.phcmp(word1, word2);
        }
        
        public string GetAppName() {
            return base.Channel.GetAppName();
        }
        
        public bool checkver(out string[] a, string sver) {
            return base.Channel.checkver(out a, sver);
        }
        
        public SemanticLinkHelper.WordFormsService.morphstr[] processmorph(string text) {
            return base.Channel.processmorph(text);
        }
        
        public string getcwf(string w) {
            return base.Channel.getcwf(w);
        }
        
        public string processaccent(string text) {
            return base.Channel.processaccent(text);
        }
        
        public string processtranscr(string text) {
            return base.Channel.processtranscr(text);
        }
        
        public bool getAllPart(out byte[] res, string inputWord) {
            return base.Channel.getAllPart(out res, inputWord);
        }
        
        public SemanticLinkHelper.WordFormsService.WordUniAndPartAndOmon[] getAllFirstWFormsWithParts(string inputWord) {
            return base.Channel.getAllFirstWFormsWithParts(inputWord);
        }
        
        public string getsemcomm(out string f6, out string f7, int uni) {
            return base.Channel.getsemcomm(out f6, out f7, uni);
        }
        
        public SemanticLinkHelper.WordFormsService.typeWord[] getTypeWords(string[] inputWords) {
            return base.Channel.getTypeWords(inputWords);
        }
        
        public string[] getGramParams(out string partName, int idpart, ushort[] grs) {
            return base.Channel.getGramParams(out partName, idpart, grs);
        }
        
        public int[] getPartIdAssotiations(out int[] commPartIds) {
            return base.Channel.getPartIdAssotiations(out commPartIds);
        }
        
        public SemanticLinkHelper.WordFormsService.partgramInfo[] getAllPartGramInfo() {
            return base.Channel.getAllPartGramInfo();
        }
        
        public SemanticLinkHelper.WordFormsService.CommonPartsInfo[] getCommonPartsInfo() {
            return base.Channel.getCommonPartsInfo();
        }
    }
}
